# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
